# Generated by Django 2.1.7 on 2019-05-17 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0007_auto_20190517_1223'),
        ('room', '0002_review_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='action_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booked_by', to='staff.employee'),
        ),
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
