# Generated by Django 2.1.7 on 2019-05-18 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0004_room_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='type',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
