# Generated by Django 2.1.7 on 2019-05-18 16:04

from django.db import migrations


class Migration(migrations.Migration):
    atomic =False
    dependencies = [
        ('room', '0007_auto_20190518_1701'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='room_types',
            new_name='room_type',
        ),
    ]
