# Generated by Django 2.1.7 on 2019-05-18 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0009_remove_room_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='room_type',
        ),
    ]
