# Generated by Django 2.1.7 on 2019-05-18 16:07

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('room', '0012_auto_20190518_1707'),
    ]

    operations = [
        migrations.DeleteModel(
            name='room_type',
        ),
    ]
