# Generated by Django 2.1.7 on 2019-05-18 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('room', '0013_delete_room_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_type', to='room.type'),
        ),
    ]
