# Generated by Django 2.1.7 on 2019-05-18 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0015_auto_20190518_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_information',
            name='count',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
