# Generated by Django 2.1.7 on 2019-05-20 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0017_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='is_room_free',
        ),
    ]
