# Generated by Django 2.1.7 on 2019-05-21 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0019_order_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='proposed_check_out_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
