# Generated by Django 2.1.7 on 2019-05-24 11:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0020_salary'),
        ('room', '0022_booking_check_out_action_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='room_type_services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(blank=True, max_length=50, null=True)),
                ('active', models.IntegerField(blank=True, default=1, null=True)),
                ('created_on', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.employee')),
            ],
        ),
        migrations.AddField(
            model_name='room_type',
            name='discount',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='room_type_services',
            name='room_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_type_service', to='room.room_type'),
        ),
    ]
