# Generated by Django 2.1.7 on 2019-05-24 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0020_salary'),
        ('room', '0023_auto_20190524_1202'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room_images',
            old_name='date',
            new_name='created_on',
        ),
        migrations.RenameField(
            model_name='room_images',
            old_name='image_filename',
            new_name='file_name',
        ),
        migrations.RemoveField(
            model_name='room_images',
            name='action_by',
        ),
        migrations.AddField(
            model_name='room_images',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image_created_by_admin', to='staff.employee'),
        ),
        migrations.AddField(
            model_name='room_images',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
