# Generated by Django 2.1.7 on 2019-05-24 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0020_salary'),
        ('room', '0025_auto_20190524_1207'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='room_type_services',
            new_name='room_type_service',
        ),
    ]
