# Generated by Django 2.1.7 on 2019-05-27 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0029_auto_20190527_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='sent_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
