# Generated by Django 2.1.7 on 2019-05-28 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0030_auto_20190527_1535'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room_type_service',
            old_name='service',
            new_name='title',
        ),
        migrations.AddField(
            model_name='room_type_service',
            name='file_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
