# Generated by Django 2.1.7 on 2019-05-28 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0022_employee_position'),
        ('room', '0031_auto_20190528_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='room_type',
            name='action_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_type_action_by', to='staff.employee'),
        ),
    ]
