# Generated by Django 2.1.7 on 2019-05-28 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0032_room_type_action_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='room_type',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
