# Generated by Django 2.1.7 on 2019-05-31 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0033_room_type_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_information',
            name='source',
            field=models.CharField(blank=True, default='staff', max_length=250, null=True),
        ),
    ]
