# Generated by Django 2.1.7 on 2019-06-04 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0034_user_information_source'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-pk']},
        ),
    ]
