# Generated by Django 2.1.7 on 2019-05-16 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='active',
        ),
        migrations.AddField(
            model_name='inventory_log',
            name='type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
