# Generated by Django 2.1.7 on 2019-05-16 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_attendance_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='date',
        ),
    ]
