# Generated by Django 2.1.7 on 2019-05-17 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0007_auto_20190517_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='department',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
