# Generated by Django 2.1.7 on 2019-05-20 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0008_employee_department'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='starting',
            new_name='current',
        ),
    ]
