# Generated by Django 2.1.7 on 2019-05-20 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0010_stock_action_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='action_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.employee'),
        ),
    ]
