# Generated by Django 2.1.7 on 2019-05-20 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0012_remove_inventory_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='closing',
        ),
        migrations.AddField(
            model_name='stock',
            name='type',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
