# Generated by Django 2.1.7 on 2019-05-20 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0013_auto_20190520_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='type',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
