# Generated by Django 2.1.7 on 2019-05-21 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0014_auto_20190520_1801'),
    ]

    operations = [
        migrations.CreateModel(
            name='authentication_level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_title', models.CharField(blank=True, max_length=100, null=True)),
                ('position_val', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_title', models.CharField(blank=True, max_length=100, null=True)),
                ('department_val', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='authentication_level',
            name='hotel_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hotel_department', to='staff.department'),
        ),
    ]
