# Generated by Django 2.1.7 on 2019-05-21 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0015_auto_20190521_1109'),
    ]

    operations = [
        migrations.CreateModel(
            name='position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('no_of_staff', models.IntegerField(blank=True, null=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.department')),
            ],
        ),
        migrations.RenameField(
            model_name='authentication_level',
            old_name='position_title',
            new_name='level_title',
        ),
        migrations.RenameField(
            model_name='authentication_level',
            old_name='position_val',
            new_name='level_val',
        ),
        migrations.RemoveField(
            model_name='authentication_level',
            name='hotel_department',
        ),
    ]
