# Generated by Django 2.1.7 on 2019-05-21 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0016_auto_20190521_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='auth_level',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='department',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
