# Generated by Django 2.1.7 on 2019-05-22 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0018_revenue'),
    ]

    operations = [
        migrations.AddField(
            model_name='revenue',
            name='type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
