# Generated by Django 2.1.7 on 2019-05-24 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0020_salary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='staff_type',
        ),
    ]
