# Generated by Django 2.1.7 on 2019-05-24 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0021_remove_employee_staff_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='position',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
