# Generated by Django 2.1.7 on 2019-05-31 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0022_employee_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='admin_conversation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversations', models.IntegerField(blank=True, default=0, null=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.employee')),
            ],
        ),
    ]
