# Generated by Django 2.1.7 on 2019-05-31 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('room', '0034_user_information_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='public_booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_date', models.DateTimeField(blank=True, null=True)),
                ('proposed_check_in_date', models.DateTimeField(blank=True, null=True)),
                ('proposed_check_out_date', models.DateTimeField(blank=True, null=True)),
                ('room_type', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='room.user_information')),
            ],
        ),
    ]
