# Generated by Django 2.1.7 on 2019-05-31 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20190531_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='public_booking',
            name='status',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
