# Generated by Django 2.1.7 on 2019-05-31 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_public_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='public_booking',
            name='status',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
