# Generated by Django 2.1.7 on 2019-06-04 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20190531_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='public_booking',
            name='adults',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='public_booking',
            name='children',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
