# Generated by Django 2.1.7 on 2019-06-05 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_public_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='public_contact',
            old_name='message',
            new_name='content',
        ),
        migrations.AddField(
            model_name='public_contact',
            name='status',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
